version: 2

# 项目元信息
project_name: terraform-provider-collection # 替换为你的项目名称
dist: dist # 输出文件夹

# 发布相关配置
release:
  github:
    owner: "w564791" # 替换为你的 GitHub 用户名
    name: "w564791" # 替换为你的代码仓库名

# 构建配置
builds:
  - id: default
    main: . # 主程序路径
    goos: 
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# 归档配置
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - license*
      - README.md

# 快速快照发布配置
snapshot:
  name_template: "{{ .Tag }}"

# 发布后动作
changelog:
  use: git
  sort: asc
